### ISSUE TITLE
How can I disable detection of die/exit ?

### ISSUE THREAD

**Issue by ywcdiao** [ekino/phpstan-banned-code#35]
Hi Ekino,

As the detection of die/exit is enabled by default in the extension.neon.
Is it possible to disable such detection in my project? If so, how to do it?

Best regards,
Weichao

**Comment by mremi** [comment]
Hi,

You can find different solutions in the official documentation:
https://phpstan.org/user-guide/ignoring-errors

If you want to disable it globally, I think you can redeclare [the parameter](https://github.com/ekino/phpstan-banned-code/blob/master/extension.neon#L12) in your project.

**Comment by ywcdiao** [comment]
Hi @mremi ,

Thank you for the explanation, I want to disable it globally.
I have tried to re-declare the parameter in my project like this:
```yaml
    banned_code:
        nodes:
            # enable detection of a set of functions
            -
                type: Expr_FuncCall
                functions:
                    - dump
                    - var_dump
```
I just want to detect these functions: "dump" and "var_dump", not "exit" or "eval".
But this did not work, it still show errors for "exit" and "eval". I think it is because this config is already defined in https://github.com/ekino/phpstan-banned-code/blob/master/extension.neon, we can not override it in our own project.
Can you advise me?

Best regards,
Weichao
